default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hello_dev
  

test:
  <<: *default
  database: hello_test

production:
  <<: *default
  database: hello_prod
